-- Create the 'tests' table to store test results
CREATE TABLE public.tests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    department text,
    service text,
    server text,
    test_name text,
    description text,
    status text,
    screenshot_urls text[] -- Array of strings to store multiple screenshot URLs
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone (anon) to INSERT data
-- For an internal documentation tool, this is often acceptable. 
-- For higher security, consider authenticated users only.
CREATE POLICY "Allow public inserts" 
ON public.tests 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Create a policy that allows anyone (anon) to READ data
CREATE POLICY "Allow public reads" 
ON public.tests 
FOR SELECT 
TO anon 
USING (true);

-- STORAGE SETUP
-- You cannot create buckets via SQL in the SQL Editor easily for all environments,
-- but you can set up the policies.
-- 1. Go to Storage > Create a new bucket named 'image' and make it PUBLIC.

-- If you want to use SQL to handle storage policies (assuming the bucket 'image' exists):

-- Allow public uploads to 'image' bucket
CREATE POLICY "Allow public uploads"
ON storage.objects
FOR INSERT
TO anon
WITH CHECK ( bucket_id = 'image' );

-- Allow public viewing of 'image' bucket
CREATE POLICY "Allow public viewing"
ON storage.objects
FOR SELECT
TO anon
USING ( bucket_id = 'image' );
